### PR TITLE
Add tidal-parse to stack config file

### LINKED ISSUE #723: stack test and cabal test don't run the same tests
I noticed that the `stack test` command pass, while the `cabal test` does not.
https://travis-ci.org/github/tidalcycles/Tidal/builds/731540188

This is because stack is not configured to launch `tidal-parse` tests (that are broken now)

### PR DESCRIPTION
**Pull request by ndr-brt**
Fixes #723

### CODE REVIEW

**Comment by ndr-brt** [comment]
I noticed that `stack test` didn't run `tidal-parse` tests.
Just adding `tidal-parse` to pacakges and `haskellish-0.2.3` to extra-deps in `stack.yaml` resolved tests on my computer with `stack test`, but then on travis failed when the options are: `--resolver lts-15.15 --system-ghc`.
It requires to add other dependencies to `stack.yaml`, but I wonder if it's the right approac...
@dktr0 can you help me on that?

**Comment by dktr0** [comment]
What are the other dependencies it requires?

**Comment by ndr-brt** [comment]
At first it tells me:
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for haskellish-0.2.3:
    template-haskell-2.15.0.0 from stack configuration does not match >=2.10.0.0 && <2.15  (latest matching version is 2.14.0.0)
needed due to tidal-parse-0.0.1 -> haskellish-0.2.3

In the dependencies for tidal-parse-0.0.1:
    template-haskell-2.15.0.0 from stack configuration does not match >=2.10.0.0 && <2.15  (latest matching version is 2.14.0.0)
needed since tidal-parse is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true' in /home/andrea/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps in /home/andrea/Code/livecoding/Tidal/stack.yaml:

- template-haskell-2.14.0.0@sha256:e3747ae9e2aeec160196706dd470b5fc4175678ec4136bcec9124534f67d83bc,1724
```

Then I add `template-haskell-2.14.0.0` to the `stack.yml` file, the next error is:
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for blaze-builder-0.4.1.0:
    text must match >=0.10 && <1.3, but this GHC boot package has been pruned (issue #4510); you need to add the package explicitly to extra-deps  (latest matching version is 1.2.4.0)
needed due to tidal-1.6.2 -> blaze-builder-0.4.1.0

In the dependencies for cabal-doctest-1.0.8:
    Cabal must match >=1.10 && <3.3, but the stack configuration has no specified version  (latest matching version is 3.2.0.0)
needed due to tidal-1.6.2 -> cabal-doctest-1.0.8

In the dependencies for comonad-5.0.6:
    Cabal needed, but the stack configuration has no specified version  (latest matching version is 3.2.0.0)
needed due to tidal-1.6.2 -> comonad-5.0.6

In the dependencies for distributive-0.6.2:
    Cabal needed, but the stack configuration has no specified version  (latest matching version is 3.2.0.0)
needed due to tidal-1.6.2 -> distributive-0.6.2

In the dependencies for template-haskell-2.14.0.0:
    base-4.13.0.0 from stack configuration does not match >=4.9 && <4.13  (latest matching version is 4.12.0.0)
    ghc-boot-th-8.8.3 from stack configuration does not match ==8.6.*  (latest matching version is 8.6.5)
needed due to tidal-parse-0.0.1 -> template-haskell-2.14.0.0

In the dependencies for tidal-1.6.2:
    parsec must match >=3.1.12 && <3.2, but this GHC boot package has been pruned (issue #4510); you need to add the package explicitly to extra-deps  (latest matching version is 3.1.14.0)
    text must match <1.3, but this GHC boot package has been pruned (issue #4510); you need to add the package explicitly to extra-deps  (latest matching version is 1.2.4.0)
needed since tidal is a build target.

Some different approaches to resolving this:

  * Build requires unattainable version of base. Since base is a part of GHC, you most likely need to use a different GHC version with the matching base.
```

That scares me a bit :D

**Comment by dktr0** [comment]
I think the problem is that the bounds on template-haskell in the tidal-parse.cabal file and in the haskellish library need to be widened to: template-haskell >= 2.10.0.0 && < 2.15

I'll do this for haskellish later this morning - more news soon.

**Comment by dktr0** [comment]
Okay I've created a new version of haskellish (0.2.3.1) with wider template-haskell bounds. I think now you can change tidal-parse.cabal as follows:
template-haskell >= 2.10.0.0 && < 2.16
haskellish >= 0.2.3.1 && < 0.3

**Comment by ndr-brt** [comment]
Perfect, now the builds are green :) 
thanks @dktr0

**Comment by dktr0** [comment]
Thanks!

**Comment by yaxu** [comment]
Thanks both!

**Pull request merged**
