### PR TITLE
Exponential double

### LINKED ISSUE #610: Be more clever when parsing ratios / note names / exponential numbers
E.g. for mini-notation of patterns of doubles the parser could guess:
* `e` - note e in the middle octave
* `e3` - note e in the third octave
* `1e` - one eighth
* `3e` - three eighths
* `3e3` - 3000

### LINKED ISSUE #870: tidal-listener not building on ghc 9.2.1
See https://github.com/haskell-hint/hint/issues/138

### PR DESCRIPTION
**Pull request by ndr-brt**
Fix #610 (not in the best way, there's need to refactor, I tried a lot but I was hard for me to do it better)
Fix #870

### CODE REVIEW

**Comment by ndr-brt** [comment]
Uhm, weird, seems like here in the PR "Some checks were not successful",
but here: https://github.com/tidalcycles/Tidal/actions/workflows/ci.yml everything is good

**Comment by ndr-brt** [comment]
Ok, I refactored `pRatio`, doing this we got some new features for free (I added some tests as documentation)

**Comment by ndr-brt** [comment]
@yaxu can we merge this?

**Comment by yaxu** [comment]
Done, thanks!

**Pull request merged**
