### PR TITLE
qualify imports, remove unused imports

### PR DESCRIPTION
**Pull request by JeffreyBenjaminBrown**
To make it easier to study these two files, I [prettied up the imports](https://wiki.haskell.org/Import_modules_properly) a little.

### CODE REVIEW

**Comment by JeffreyBenjaminBrown** [comment]
How can the build have failed? I only changed the imports. It builds on my machine ...

**Comment by bgold-cosmos** [comment]
I think the main thing is you removed `Control.Applicative` from Stream.hs, which breaks things for GHC versions before the "Functor-Applicative-Monad Proposal" was implemented in 7.10.

**Comment by JeffreyBenjaminBrown** [comment]
It worked! Thanks, Ben!

**Comment by yaxu** [comment]
Thakns for this @JeffreyBenjaminBrown but can you target the active development branch 1.0-dev instead of master please

**Comment by JeffreyBenjaminBrown** [comment]
I nuked the repo that sent this pull request, created another one, switched to branch 1.0-dev (Git wouldn't let me switch to remotes/origin/1.0-dev except in detached head state), and sent from there. Hope that works.

**Comment by yaxu** [comment]
Sorry about the hassle here, we need to make the active dev branch clear somehow..

**Comment by JeffreyBenjaminBrown** [comment]
It's all good! I think I would have recognized it if I had looked -- I just wasn't in the habit of using branches.

**Pull request closed without merging**
