### PR TITLE
patternize someCyclesBy

### PR DESCRIPTION
**Pull request by bgold-cosmos**

### CODE REVIEW

**Comment by yaxu** [comment]
Thanks! I'll look into while the travis build isn't working

**Comment by bgold-cosmos** [comment]
Travis complains about a failure building tidal-parse, but it looks like my attempt to fix it by updating the signature of `sometimesBy` wasn't enough.

**Comment by yaxu** [comment]
Yes I spotted the problem, fixing..

**Comment by yaxu** [comment]
Hopefully fixed in https://github.com/tidalcycles/Tidal/commit/2049766f34e200180c385486cce4cf45589ea1b2

**Comment by kindohm** [comment]
I sense that this feature introduced a bug: https://github.com/tidalcycles/Tidal/issues/632

**Pull request merged**
