### PR TITLE
added to tidal-parse: toScale, arpeggiate, arp, weave, weaveWith, ghost, inside, outside, inv

### PR DESCRIPTION
**Pull request by dktr0**
I'm not sure why there are a bunch of old commits being included in this pull request - I thought most of that was merged ages ago.

### CODE REVIEW

**Comment by yaxu** [comment]
I think it's probably harmless but have a look at contributing.md for an approach to merging upstream stuff that might help avoid the commit confusion

**Comment by yaxu** [comment]
It looks like the Travis build is more generally broken, for now it's worth making sure cabal test runs OK locally if you haven't already

**Comment by dktr0** [comment]
thanks - yeah, I did cabal test before committing.

**Comment by dktr0** [comment]
Not sure I follow the comment about contributing.md. Are you suggesting the confusion happens because my branch is also named main?

**Comment by yaxu** [comment]
@dktr0 Sorry was on my phone. 

I meant this bit: https://github.com/tidalcycles/Tidal/blob/main/CONTRIBUTING.md#recommendations-to-handle-forks-and-branches

When I update my fork by creating a PR from upstream to downstream, I end up with the commits reappearing when I try making a PR back to upstream. The procedure described there seems to avoid this. YMMV!

**Pull request merged**
