### PR TITLE
david minnix - implemented soak

### PR DESCRIPTION
**Pull request by XiNNiW**
Hi folks,

I implemented a function called "soak" for repeatedly applying a function to a pattern and combining the results together with cat. This can be a cool way to spin out variations for both melodic and rhythmic patterns. 

For example:
d1 $ (note $ scale "hexPhrygian" $ soak ((0.25 <~).(+ irand(2))) 4 "0 . 2 3 ~ . 0 1 . -1 -2") #s "gtr"

will create a wandering melodic phrase that returns to the original after 4 cycles. 

d1 $ soak (iter 8. slow 2 .ply 3) 4 $ euclid 3 5 $ sound "bd sn"

will build up a kick rush over 4 bars

Let me know what you think. ~~I'm not crazy about the name but I think It could be used for some cool stuff.~~ I changed the name to soak which I think is a better descriptor. 

Thanks,

David

### CODE REVIEW

**Comment by yaxu** [comment]
Nice! What do you think about swapping the parameters? Depth comes first for `stut`/`stutWith`, and I find it clearer to put the 'least complicated' parameter first - in your examples the depth parameter gets kind of lost after the function.

**Comment by XiNNiW** [comment]
Sounds great! I'll switch them around and commit again.

**Comment by XiNNiW** [comment]
Hey alex, I think this one might be ready to go. The parameters have been swapped to put depth first.

Now it looks like this in use:

`d1 $ soak 4 (iter 8. slow 2 .ply 3) $ euclid 3 5 $ sound "bd sn"`

**Comment by yaxu** [comment]
Thanks, will merge! We might tweak the name later to create a family of functions but I like the name soak..

**Pull request merged**
