### PR TITLE
change streamGetnow to factor in the processAhead and also destroy the sessionstate

### PR DESCRIPTION
**Pull request by polymorphicengine**

### CODE REVIEW

**Comment by Zalastax** [comment]
What is the expected behavior here? To get the cycle that would right now be hitting the speakers or roughly get the cycle that we would be processing at this moment? Reading the old code it seems like the latter is what was used, which would correspond to the change you are proposing. But I want us to reflect on what is most useful. Do we have some clear use cases for this function? If it is most used for the `once` function, then adding `processAhead` seems somewhat wrong.

The old code:
https://github.com/tidalcycles/Tidal/blob/a05892257b5be001d1161b9b0849395f11cf5ef7/src/Sound/Tidal/Stream.hs#L714-L717

**Comment by polymorphicengine** [comment]
> Do we have some clear use cases for this function?

The intended use is when someone wants to use the time of the stream to query a pattern for something (for example to highlight the pattern in the editor). When using this i encountered that with fast speeds there was a misalignment with the event that was playing and the one that was being highlighted. Adding the processAhead fixed the issue for me.

so maybe we should rename this function to something else and keep the old one as streamGetnow?

**Comment by Zalastax** [comment]
Great idea!

What about `processGetAhead`?

**Comment by polymorphicengine** [comment]
i named it `streamGetAhead` now :)

**Review by Zalastax — APPROVED** [review]
Good catch, that's better and probably what I actually meant 😸 Great job!

**Comment by yaxu** [comment]
Is this ready to merge?

**Comment by polymorphicengine** [comment]
i think so!

**Comment by yaxu** [comment]
Thanks a lot!

**Pull request merged**
