### PR TITLE
Fix dotick tempo

### PR DESCRIPTION
**Pull request by jwaldmann**

### CODE REVIEW

**Comment by jwaldmann** [comment]
Travis shows these errors:
* StrictData not available for ghc before 8 
* stack cannot build current hosc
I'm not sure what's the best way to handle these. I am adding them to #667

**Comment by yaxu** [comment]
Let's aim for ghc 7 compatibility and wait for hosc to be released. Note that upper bound for hosc will need changing in tidal.cabal

**Comment by telephon** [comment]
generating arrays via tidal and sending them to superdirt as parameters may open some interesting possibilities.

**Comment by jwaldmann** [comment]
I amended the patch. It builds on travis, and it seems to work. Can anyone confirm? Running (i.e., start `sclang` and actually listen to) test/dontcrash  (I use `stack --resolver=lts test :dontcrash`)

**Comment by yaxu** [comment]
@jwaldmann I get immediate response timeout from that stack command, but `cabal v1-test` runs the test successfully. Is this ready for merge then?

**Comment by yaxu** [comment]
@telephon I don't follow, did you post on the wrong issue? :)

**Comment by yaxu** [comment]
@jwaldmann Just a bump.. Do you think this is ready for merge?

**Comment by jwaldmann** [comment]
Yes, merge. 

Turns out that modifyVar and proper placement of handler was enough, and I didn't need the strictness annotations. But we definitely should have them sometime.

I am slightly worried about your 

> immediate response timeout

For me, when no sclang is running:
```
time stack --resolver=lts test :dontcrash
Selected resolver: lts-16.0
tidal> test (suite: dontcrash)

Listening for controls on 127.0.0.1:6010
--- playing test pattern 0 -----
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
---------------- playing simple pattern
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
--- playing test pattern 1 -----
Failed to send. Is the 'SuperDirt' target running? Network.Socket.sendBuf: does not exist (Connection refused)
Failed to Stream.doTick: Syntax error in sequence:
  "0."
     ^  
unexpected end of input
expecting fraction
Return to previous pattern.
...
tidal> Test suite dontcrash passed

real	0m18.261s
user	0m1.945s
sys	0m0.324s
```
with `sclang` running:
```
time stack --resolver=lts test :dontcrash
Selected resolver: lts-16.0
tidal> test (suite: dontcrash)

Listening for controls on 127.0.0.1:6010
--- playing test pattern 0 -----
---------------- playing simple pattern
--- playing test pattern 1 -----
Failed to Stream.doTick: Syntax error in sequence:
  "0."
     ^  
unexpected end of input
expecting fraction
Return to previous pattern.
---------------- playing simple pattern
--- playing test pattern 2 -----
Error in pattern: Syntax error in sequence:
  "<0.5 2?"
          ^  
unexpected end of input
expecting "-", "+", digit, "w", "h", "q", "e", "s", "t", "f", "x", rest, "[", "{", "<", "^", ".", "," or ">"
---------------- playing simple pattern
--- playing test pattern 3 -----
---------------- playing simple pattern

tidal> Test suite dontcrash passed

real	0m19.668s
user	0m2.072s
sys	0m0.494s
```

**Comment by yaxu** [comment]
Done, thanks!

I'm not sure what's up with stack, I don't usually use it.
```
alex@stanage:~/tmp/Tidal$ stack --resolver=lts test :dontcrash
Selected resolver: lts-16.0
Downloading lts-16.0 build plan ...RedownloadFailed Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-16.0.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 "/home/alex/.stack/build-plan/lts-16.0.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),("Strict-Transport-Security","max-age=31536000"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("Content-Type","text/plain; charset=utf-8"),("Via","1.1 varnish (Varnish/6.0)"),("X-GitHub-Request-Id","4E4C:69EC:5B92DC:6F7A33:5EE008C3"),("Accept-Ranges","bytes"),("Date","Tue, 09 Jun 2020 22:10:12 GMT"),("Via","1.1 varnish"),("X-Served-By","cache-lon4236-LON"),("X-Cache","HIT, MISS"),("X-Cache-Hits","1, 0"),("X-Timer","S1591740613.585783,VS0,VE78"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","b41ed1dbbaac2bdc92ae9e6a2ca9f44d714f6993"),("Expires","Tue, 09 Jun 2020 22:15:12 GMT"),("Source-Age","0")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})
```

**Comment by jwaldmann** [comment]
What is your `stack --version`? I have `Version 2.3.1 x86_64 hpack-0.33.0`. Perhaps yours is too old to understand the current format of indices/files it gets from the server.

I think stack really solves the "independent and reproducible builds" problem. It does however have a tendency of downloading binaries (ghc, and stack itself when upgrading), so I make sure to put `install-ghc: false; system-ghc: true` in `$HOME/.stack/config.yaml`.

But if you avoid  binaries, then you're in for the fun ride of bootstrapping stack from source. Here's one way to do it ... https://github.com/commercialhaskell/stack/issues/5132#issuecomment-589755221

**Comment by yaxu** [comment]
I'm on version 1.5.1. Thanks for the tips. There seems to be a fight between cabal and stack proponents, and neither seems well documented, so it's hard to understand the picture. In its current state, cabal v2 does not meet my needs, though.

**Pull request merged**
