### PR TITLE
tidal-parse: updated dependency bounds; ControlMap replaced with Valu…

### PR DESCRIPTION
**Pull request by dktr0**
…eMap

### CODE REVIEW

**Comment by dktr0** [comment]
This incorporates the wider bounds on template-haskell - same failing test result on the stack build as before with the stack build grabbing a much older version of Haskellish. I'm wondering if this would succeed without "allow-newer" in the stack configuration. Is there a good reason allow-newer is enabled?

**Comment by dktr0** [comment]
oh wait now I think I see it - the specific (old) version of haskellish is named in the stack configuration!

**Comment by dktr0** [comment]
Have updated - fingers crossed...

**Comment by dktr0** [comment]
I remember now: anything that isn't in a stack snapshot MUST be referenced by a specific pinned version.

**Comment by dktr0** [comment]
Hurray - now the stack one builds.

**Comment by yaxu** [comment]
Great thanks! Maybe it's worth putting haskellish in stackage? If I remember right, it's just a case of listing it with a maintainer in this file: https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml

I'm actually listed as the maintainer of hosc, because Rohan didn't want the bother, so could take haskellish there too if you prefer.

On the other hand might not gain a huge amount from having haskellish in stackage at the moment.

By the way sorry for breaking tidal-parse, will try to remember to test changes there in the future.

**Comment by dktr0** [comment]
I'll probably do this sometime soon. I'm not sure it will help economize tidal-parse work that work - I kind of expect there will often be reasons to pin specific versions, as Haskellish evolves (not exactly rapidly, but not exactly stable/old hat either...).

**Pull request merged**
