### PR TITLE
Add listener build workflows

### PR DESCRIPTION
**Pull request by ndr-brt**
Ref #850 and #315 
Adapted from https://github.com/polymorphicengine/tidal-gui
They will run only after a tag with the format `*.*.*`, so only after a tidal release.
Tested on my fork.

### CODE REVIEW

**Comment by yaxu** [comment]
Excellent!

**Comment by ndr-brt** [comment]
Ok, I noticed that the branch was not rebased to main, I updated it

**Comment by yaxu** [comment]
Thanks :)

**Comment by yaxu** [comment]
So @ndr-brt how does this work, where do the binaries end up? Are we able to trigger this without doing a release, for testing things out?

**Comment by ndr-brt** [comment]
If I remember well, the `release` action needs a tag to be executed, so it creates a release with the binaries in the "releases" section. Maybe @polymorphicengine can correct me if I'm wrong

**Comment by ndr-brt** [comment]
To test maybe we could make that run at every push, not only when there's a tag, then set the release step to run only when there's a tag

**Comment by polymorphicengine** [comment]
yes that's correct. To try it out just change it to 
```
on:
  push:
    branches: [ main ]
```
I don't know how to conditionally run a step when there is a tag from the top of my head but it should be possible.

**Pull request merged**
