### PR TITLE
add newline so atom package can handle BootTidal.hs correctly

### PR DESCRIPTION
**Pull request by bgold-cosmos**

### CODE REVIEW

**Comment by ndr-brt** [comment]
could be cleaner with the `:{ :}` block? e.g.
```haskell
:{
import Sound.Tidal.Context
import System.IO (hSetEncoding, stdout, utf8)
hSetEncoding stdout utf8
:}
```

**Comment by bgold-cosmos** [comment]
I don't think multiple imports within a `:{` `:}` block work in the current version of GHCi (I know it was broken in the past).

**Comment by yaxu** [comment]
Thanks will release this in the morning.. 
It works for me in emacs, which I think loads the file using :script
Maybe atom should do the same?

**Comment by bgold-cosmos** [comment]
Yes, long-term that's probably better, but right now it uses the same reformatting functions that ctrl-enter uses.

**Comment by ndr-brt** [comment]
Ok, new issue:
https://github.com/tidalcycles/atom-tidalcycles/issues/85

**Comment by yaxu** [comment]
I've released it now, thanks for the catch @bgold-cosmos

**Pull request merged**
