### PR TITLE
Patternize the first parameter of fit

### PR DESCRIPTION
**Pull request by bgold-cosmos**

### CODE REVIEW

**Comment by yaxu** [comment]
Thanks! I'll fix up tidal-parse

**Comment by BenjaminWynn** [comment]
Thanks so much for this!!

And pardon my ignorance on how GitHub works, but since the change has been committed does that mean that I can update using the normal method?
```
cabal v1-update
cabal v1-install tidal
```

**Comment by jwaldmann** [comment]
`cabal install` pulls from hackage https://hackage.haskell.org/package/tidal

Any change here in the repo needs to be pushed there (by Alex). He normally collects several changes before doing so.

**Comment by yaxu** [comment]
I've just done a release now so that should work.

**Comment by BenjaminWynn** [comment]
Got it. Thanks so much all!

**Pull request merged**
