### PR TITLE
include addN domN chords

### PR DESCRIPTION
**Pull request by cleary**
add some extra common chord types

`nine` was a duplicate of `add9`, so it got aliased

### CODE REVIEW

**Comment by yaxu** [comment]
Is this ready to be merged?

**Comment by cleary** [comment]
Yes it is, thankyou!

**Comment by yaxu** [comment]
Great thanks! Will release 1.7.2 soon :)

**Comment by cleary** [comment]
Apologies, there were a ton of errors in there... not sleeping much at the moment and it's showing :(

**Comment by yaxu** [comment]
Thanks!

**Pull request merged**
