### PR TITLE
overhaul of the parser

### PR DESCRIPTION
**Pull request by polymorphicengine**
i kind of messed up when trying to update my last PR, sorry about that (still trying to figure out how to do this github thing)

it's the same code as before, so still needs some choices where to be more liberal with whitespace and where to be more strict.

as has been suggested i might also try out mega-parsec in the future

### CODE REVIEW

**Comment by yaxu** [comment]
:)

**Comment by yaxu** [comment]
Does this need redoing for the current dev branch?

**Comment by polymorphicengine** [comment]
i don't think so, it was merged before

**Comment by polymorphicengine** [comment]
i have had some plans to do an overhaul again, possibly switching to a parser generator. will take some time though

**Comment by yaxu** [comment]
Ok I'll mark as done on #1076 for now

**Pull request merged**
