### PR TITLE
david minnix -- implemented function for listing out all of the chord…

### PR DESCRIPTION
**Pull request by XiNNiW**
…s tidal can make in a pattern

Super simple function. I found the one for listing scales super useful so I made one for listing the chords.

### CODE REVIEW

**Comment by XiNNiW** [comment]
Good point! I did it out habit. (test driving is pretty drilled into me) I'll delete it.

**Comment by XiNNiW** [comment]
Good point! I did it out habit. (test driving is pretty drilled into me) I'll delete it.

**Comment by XiNNiW** [comment]
Gone!

**Comment by yaxu** [comment]
Thanks a lot! I guess the test wasn't doing any harm, and I'm not fully up to date with testing philosophies, but hey!

**Comment by XiNNiW** [comment]
No prob! To me, it depends on what your building. I think your right. For someone just trying to add a chord to tidal, the burden of changing it in two places outweighs the benefit of increased documentation (the function is very simple) and early warning system for issues. (like you said, not much logic in there!)

**Pull request merged**
