### PR TITLE
Topic enum parse

### PR DESCRIPTION
**Pull request by yaxu**

### CODE REVIEW

**Comment by vivid-synth** [comment]
@yaxu the change to GADTs isn't required for this. I just got it to compile with the old definition , plus:

```haskell
   | TPat_Enum
   | TPat_EnumFromTo (TPat a) (TPat a)
   | TPat_EnumFromThenTo (TPat a) (TPat a) (TPat a)
```

GADTs are a pretty big sledgehammer (they break some type inference, for example, and turn on a lot of other extensions that have unexpected implications, like ```-XMonoLocalBinds```). You don't need the ```Parseable a => ``` constraint on the datatype itself if it's on the functions that use it (which it is).

**Comment by vivid-synth** [comment]
In addition, I don't think we necessarily *want* to restrict Tidal patterns to containing data which is Parseable.

**Comment by yaxu** [comment]
Thanks @vivid-synth, have you got this ready for a PR?

**Comment by vivid-synth** [comment]
@yaxu what branch should I base the work off?

**Comment by yaxu** [comment]
1.0-dev please!

**Pull request merged**
