### PR TITLE
a fix to unwrap' so fit' will work again

### PR DESCRIPTION
**Pull request by bgold-cosmos**

### CODE REVIEW

**Comment by yaxu** [comment]
What do you think about the above, @bgold-cosmos ? I can have a look at these things if you like

**Comment by bgold-cosmos** [comment]
OK, looking at this more I _think_ the `unwrap'` that `fit'` has been using is actually the same as `unwrapSqueeze`.  The implementations are rather different, though, so I'm going to try thinking of some weird test cases to see if there's any difference.  If not, then I can just get rid of `unwrap'` and have `fit'` refer to `unwrapSqueeze`.

**Comment by yaxu** [comment]
Aha, well spotted!

Ok so thinking about the name.. `unwrap` is actually `join` (except we can't directly define it as that due to the way monads are structured in haskell or something). It uses structure from both inner and outer patterns.

`innerJoin` only uses structure from inner patterns, and `outerJoin` from outer patterns.

`unwrapSqueeze` is like `unwrap`/`join` in that it uses structure from both patterns, but with a different strategy.. 

Well, I can't think of a better name for this than `joinSqueeze` at the moment.

Btw `unwrapSqueeze` (or `unwrap'`) isn't used very much at the moment, I think there is likely some untapped functionality here in patterning patterns in interesting ways..

**Comment by bgold-cosmos** [comment]
OK, I've updated this and tested it out.  `unwrapSqueeze` and `unwrap'` were indeed identical in intent. So I did a few things:

  * fixed a big in unwrapSqueeze
  * renamed unwrapSqueeze to squeezeJoin
  * removed the redundant unwrap'
  * updated functions using unwrap' to refer to squeezeJoin

**Comment by yaxu** [comment]
Looks great, thanks very much!

**Pull request merged**
